name: CI/CD - Build and Deploy JAR

on:
  push:
    branches:
      - main  # 监听 main 分支的推送

jobs:
  build:
    name: Build JAR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-app
          path: target/*.jar

  deploy:
    name: Deploy to Ubuntu Server
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: spring-boot-app

      - name: Transfer JAR to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "demo-0.0.1-SNAPSHOT.jar"
          target: "/home/project/test1"

      - name: Restart Spring Boot Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/project/test1
            echo "Stopping old application..."
            sudo pkill -f "demo-0.0.1-SNAPSHOT.jar" || echo "No running process found"
            echo "Starting new application..."
            nohup java -jar demo-0.0.1-SNAPSHOT.jar --server.port=8080 > app.log 2>&1 &
            echo "Deployment finished!"
