name: CI/CD - Build and Deploy JAR

on:
  push:
    branches:
      - main  # 监听 main 分支的推送

jobs:
  build:
    name: Build JAR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-app
          path: target/*.jar

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build JAR
        run: mvn clean package -DskipTests

      - name: Check JAR file before SCP
        run: |
          if [ -f target/*.jar ]; then
            echo "JAR file found, proceeding with SCP."
          else
            echo "JAR file not found! Build might have failed."
            exit 1
          fi

      - name: Remove old JAR file on remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            if [ -f /home/project/test1/demo-0.0.1-SNAPSHOT.jar ]; then
              echo "Removing old JAR file..."
              sudo rm /home/project/test1/demo-0.0.1-SNAPSHOT.jar
            fi

      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "target/*.jar"
          target: "/home/project/test1"

      - name: Restart Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/project/test1
            echo "Stopping old application..."

            echo "Starting new application..."
            nohup java -jar target/demo-0.0.1-SNAPSHOT.jar --server.port=8080 > app.log 2>&1 &

            echo "Deployment finished!"

